### ISSUE TITLE
Add custom vitest plugin

### ISSUE THREAD

**Issue by ufoscout** [nickbreaton/vitest-svelte-kit#3]
I am trying to test a graphql call performed with `@urql/svelte` but, during the test, every call returns a `[Network] fetch is not defined` error; so, I would like to add the `@rollup/plugin-graphql` vite plugin to the configuration as shown [here](https://github.com/vitest-dev/vitest/blob/main/examples/graphql/vite.config.ts).

Is there a way to add a custom plugin to this `vite.config.js` file:
```javascript
import { extractFromSvelteConfig } from "vitest-svelte-kit"
export default extractFromSvelteConfig()
```

BTW, as the graphql call works without issues when running the sveltekit application (both in SSR as in the client), so I am not sure if this is a problem of a missing plugin or a problem with `vitest-svelte-kit`

**Comment by nickbreaton** [comment]
Just as an update, I believe what's happening here is unrelated to the custom plugin. That can be added to the vite config within your `svelte.config.js` file (which it likely is already there).

I think the actual is caused by a lack of `fetch` being polyfilled. Looking to add this shortly but need to get some things worked out.
