### ISSUE TITLE
Export kit-module-emulator

### ISSUE THREAD

**Issue by benbender** [nickbreaton/vitest-svelte-kit#6]
I would like to ask if it would be possible to export the `kitModuleEmulator`-plugin? 

I was thinking of using it in https://github.com/storybookjs/builder-vite instead of mocking the sveltekit-modules by myself. 

Thank you!

**Comment by nickbreaton** [comment]
Sure I can take a look at doing this, I would also encourage you to track https://github.com/sveltejs/kit/issues/4329 which would essentially deprecate this project and would provide official functionality for what you're asking for.

I'll likely just expose this in the package itself so something like `import x from 'vitest-svelte-kit/emulator'` since I don't want to encourage others to do depend on this. Official support would be more beneficial to the community at large imo.

**Comment by benbender** [comment]
Hey thanks for the hint! I'll have a look!

A sub-export is perfectly fine to me and I would agree, that an official solution would be the better way to go. Atm, most recommended solutions out there are just plain broken remappings of the internal `sveltekit`-modules and are bound to brake at some point. In this context, your solution is an improvement until something official arrives :)

**Comment by benmccann** [comment]
`@sveltejs/kit/experimental/vite` [has been released](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next353) in `@sveltejs/kit` version `1.0.0-next.353`. Feedback welcome in https://github.com/sveltejs/kit/issues/5184
